version: '3.1'

services:

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports:
     - '6543:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local